### PR TITLE
feat: update to sdk 8

### PR DESCRIPTION
**Pull request by ewanharris**
I believe this should be most if not all of the changes required to adapt the existing codebase to SDK 8. I've attempted to break it down so that each commit is reviewable and indicative of the changes that an end user might encounter in the upgrade process.

The majority of the getter/setter movement was doing using [codemods](https://github.com/ewanharris/titanium-codemods).

Also, seeing as some of the new alloy features require a newer version of Alloy it might be good to add some like the minVersion check Fokke had [here](https://github.com/appcelerator-developer-relations/appc-sample-ti520/blob/master/app/alloy.jmk)

### CODE REVIEW

**Comment by TheeAndre** [comment]
Hey @ewanharris,
Who else needs to review your commits? I have free time for some API enhancements & wanted to pull a clean with your changes?

**Comment by jquick-axway** [comment]
@ewanharris , the "gradient.js" function `handleTouchMove()` has an if-android check to convert the touch coordinates from pixels to the default units. This coordinate conversion is no longer needed as of 8.0.0 (see [TIMOB-25839](https://jira.appcelerator.org/browse/TIMOB-25839)), but should probably be kept if running with an older SDK version.
https://github.com/appcelerator/kitchensink-v2/blob/master/app/controllers/controls/views/gradients.js#L67

For your info, you can test this by displaying a radial gradient and then touch/drag the circle. The circle will center itself under your finger as you drag.

**Comment by ewanharris** [comment]
@TheeAndre, I imagine I'll ping some of the SDK team to review this but if you'd like to leave a review yourself feel free!

@jquick-axway, gah my bad. I remember your ping about that now! I'll fix it tomorrow, I think for the code in this repo we always expect it to be ran against the version in the tiapp at a minimum so I'll just remove the code altogether.

**Comment by jquick-axway** [comment]
@ewanharris , the "phone/geolcation" crashes on Android, because it's using a deprecated `Ti.Geolocation.PROVIDER_GPS` constant that we deleted as of 8.0.0. The issue is here...
https://github.com/appcelerator/kitchensink-v2/blob/master/app/controllers/phone/geolocation.js#L8

Would you mind deleting the following line from the code above please? That will solve it.
```javascript
Ti.Geolocation.preferredProvider = Ti.Geolocation.PROVIDER_GPS;
```

FYI: The `Ti.Geolocation.PROVIDER_*` constants were replaced by the `Ti.Geolocation.Android.PROVIDER_*` constants, but it looks like the docs haven't been updated to indicate this. I'll look into update the docs. Thanks.

**Comment by jquick-axway** [comment]
The "soundLocal.js" has 2 issues that existed before 8.0.0 as well.

---
**Issue 1:**
The sound fails to play on Android since relative paths to "assets" (not required-in JS files) are currently handled differently between Android and iOS. On Android, asset paths are relative to the JS file. On iOS, asset paths are relative to the "Resources" directory. The solution for the moment is to use an absolute path instead.
https://github.com/appcelerator/kitchensink-v2/blob/master/app/controllers/phone/soundLocal.js#L15

The solution is to change sound URL from a relative path...
`'sounds/cricket.wav'`
...to absolute...
`'/sounds/cricket.wav'`

I've tested the above and it works on both Android and iOS.

---
**Issue 2:**
The playback progress bar at the bottom is mishandled on iOS, but works fine on Android. It's an issue with our `soundPlayer.getTime()` calculation. On Android, the "time" property returns milliseconds. On iOS, the "time" property returns seconds. See [TIMOB-18925](https://jira.appcelerator.org/browse/TIMOB-18925). We'll need to do a platform check before calculating the time.
https://github.com/appcelerator/kitchensink-v2/blob/master/app/controllers/phone/soundLocal.js#L76

**Comment by jquick-axway** [comment]
Titanium 8.0.0's Android `TabGroup` has been completely rewritten and this project's "custom_theme.xml" tab styles no longer have any effect on the tabs. The tab text use to be **white**, but are now **black**. We need to make some adjustments.

---
In the "custom_theme.xml" file [here](https://github.com/appcelerator/kitchensink-v2/blob/master/app/platform/android/res/values/custom_theme.xml), delete the following XML elements.
```xml
<item name="actionBarTabTextStyle">@style/TabStyle</item>
<item name="android:actionBarTabTextStyle">@style/TabStyle</item>
```

And delete the following from the same file...
```xml
<style name="TabStyle" parent="style/Widget.AppCompat.Light.ActionBar.TabText">
	<item name="android:textColor">#ffffff</item>
</style>
```

---
To set the tab text white, add the following...
```
'Tab[platform=android]': {
    activeTitleColor: 'white',
    titleColor: 'white'
}
```
...to files:
- [app/styles/console/index.tss](https://github.com/appcelerator/kitchensink-v2/blob/master/app/styles/console/index.tss)
- [app/styles/controls/index.tss](https://github.com/appcelerator/kitchensink-v2/blob/master/app/styles/controls/index.tss)
- [app/styles/mashups/index.tss](https://github.com/appcelerator/kitchensink-v2/blob/master/app/styles/mashups/index.tss)
- [app/styles/phone/index.tss](https://github.com/appcelerator/kitchensink-v2/blob/master/app/styles/phone/index.tss)

**Comment by ewanharris** [comment]
@janvennemann, updated to 8.0.1.GA

**Pull request merged**
